export const interestList = [
  { id: 1, value: "헬스", isInterested: false },
  { id: 2, value: "요가", isInterested: false },
  { id: 3, value: "필라테스", isInterested: false },
  { id: 4, value: "러닝", isInterested: false },
  { id: 5, value: "홈트레이닝", isInterested: false },
  { id: 6, value: "축구", isInterested: false },
  { id: 7, value: "야구", isInterested: false },
  { id: 8, value: "농구", isInterested: false },
  { id: 9, value: "테니스", isInterested: false },
  { id: 10, value: "배드민턴", isInterested: false },
  { id: 11, value: "등산", isInterested: false },
  { id: 12, value: "수영", isInterested: false },
  { id: 13, value: "골프", isInterested: false },
  { id: 14, value: "볼링", isInterested: false },
  { id: 15, value: "자전거/사이클", isInterested: false },
  { id: 16, value: "기타", isInterested: false },
];